# Generated by Django 4.1.7 on 2023-05-16 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('any', 'Any'), ('forest', 'Forest'), ('island', 'Island'), ('tropical', 'Tropical'), ('taiga', 'Taiga'), ('plateau', 'Plateau'), ('mountain', 'Mountain'), ('desert', 'Desert'), ('tundra', 'Tundra'), ('swamp', 'Swamp'), ('ocean', 'Ocean'), ('plains', 'Plains'), ('jungle', 'Jungle'), ('volcano', 'Volcano'), ('cave', 'Cave'), ('city', 'City'), ('castle', 'Castle'), ('dungeon', 'Dungeon'), ('ruins', 'Ruins'), ('graveyard', 'Graveyard'), ('cemetery', 'Cemetery'), ('temple', 'Temple'), ('church', 'Church'), ('library', 'Library'), ('school', 'School'), ('hospital', 'Hospital'), ('museum', 'Museum'), ('zoo', 'Zoo'), ('farm', 'Farm'), ('factory', 'Factory'), ('mine', 'Mine'), ('laboratory', 'Laboratory')], max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('rarity', models.PositiveIntegerField()),
                ('category', models.CharField(choices=[('weapon', 'Weapon'), ('armor', 'Armor'), ('consumable', 'Consumable'), ('tool', 'Tool'), ('misc', 'Misc'), ('magic', 'Magic'), ('artifact', 'Artifact'), ('quest', 'Quest'), ('key', 'Key'), ('currency', 'Currency'), ('container', 'Container'), ('clothing', 'Clothing'), ('food', 'Food'), ('drink', 'Drink'), ('vehicle', 'Vehicle'), ('animal', 'Animal'), ('plant', 'Plant'), ('furniture', 'Furniture'), ('jewelry', 'Jewelry'), ('book', 'Book'), ('music', 'Music'), ('art', 'Art'), ('gem', 'Gem'), ('mineral', 'Mineral'), ('metal', 'Metal'), ('wood', 'Wood'), ('stone', 'Stone'), ('leather', 'Leather'), ('cloth', 'Cloth'), ('paper', 'Paper'), ('glass', 'Glass'), ('plastic', 'Plastic'), ('bone', 'Bone'), ('shell', 'Shell'), ('hide', 'Hide'), ('feather', 'Feather'), ('scale', 'Scale'), ('fur', 'Fur'), ('spice', 'Spice'), ('herb', 'Herb'), ('oil', 'Oil'), ('ink', 'Ink'), ('dye', 'Dye'), ('paint', 'Paint'), ('potion', 'Potion'), ('scroll', 'Scroll'), ('spell', 'Spell'), ('wand', 'Wand')], max_length=50)),
                ('damage_dice', models.CharField(blank=True, max_length=10, null=True)),
                ('damage_type', models.CharField(blank=True, max_length=50, null=True)),
                ('critical', models.CharField(blank=True, max_length=50, null=True)),
                ('armor_class', models.IntegerField(blank=True, null=True)),
                ('armor_type', models.CharField(blank=True, max_length=50, null=True)),
                ('property', models.CharField(blank=True, max_length=50, null=True)),
                ('power', models.CharField(blank=True, max_length=50, null=True)),
                ('biomes', models.ManyToManyField(blank=True, to='caravan.biome')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Trader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('starting_gold', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('biomes', models.ManyToManyField(to='caravan.biome')),
            ],
        ),
        migrations.CreateModel(
            name='TradersItemMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caravan.item')),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caravan.trader')),
            ],
            options={
                'unique_together': {('trader', 'item')},
            },
        ),
        migrations.AddField(
            model_name='trader',
            name='items',
            field=models.ManyToManyField(blank=True, through='caravan.TradersItemMeta', to='caravan.item'),
        ),
        migrations.AddField(
            model_name='trader',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caravan.job'),
        ),
        migrations.AddField(
            model_name='item',
            name='job_requirements',
            field=models.ManyToManyField(blank=True, to='caravan.job'),
        ),
        migrations.CreateModel(
            name='Caravan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('biome', models.CharField(choices=[('any', 'Any'), ('forest', 'Forest'), ('island', 'Island'), ('tropical', 'Tropical'), ('taiga', 'Taiga'), ('plateau', 'Plateau'), ('mountain', 'Mountain'), ('desert', 'Desert'), ('tundra', 'Tundra'), ('swamp', 'Swamp'), ('ocean', 'Ocean'), ('plains', 'Plains'), ('jungle', 'Jungle'), ('volcano', 'Volcano'), ('cave', 'Cave'), ('city', 'City'), ('castle', 'Castle'), ('dungeon', 'Dungeon'), ('ruins', 'Ruins'), ('graveyard', 'Graveyard'), ('cemetery', 'Cemetery'), ('temple', 'Temple'), ('church', 'Church'), ('library', 'Library'), ('school', 'School'), ('hospital', 'Hospital'), ('museum', 'Museum'), ('zoo', 'Zoo'), ('farm', 'Farm'), ('factory', 'Factory'), ('mine', 'Mine'), ('laboratory', 'Laboratory')], max_length=50)),
                ('level', models.IntegerField()),
                ('traders', models.ManyToManyField(blank=True, to='caravan.trader')),
            ],
        ),
    ]
