# Generated by Django 4.1.7 on 2023-03-31 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caravan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trader',
            name='caravan',
        ),
        migrations.AddField(
            model_name='caravan',
            name='traders',
            field=models.ManyToManyField(blank=True, to='caravan.trader'),
        ),
    ]
