# Generated by Django 4.1.7 on 2023-03-31 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caravan', '0002_remove_trader_caravan_caravan_traders'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='biomes',
            field=models.ManyToManyField(to='caravan.biome'),
        ),
        migrations.AddField(
            model_name='trader',
            name='biomes',
            field=models.ManyToManyField(to='caravan.biome'),
        ),
    ]
