# Generated by Django 4.1.7 on 2023-03-31 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caravan', '0003_biome_item_biomes_trader_biomes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biome',
            name='name',
            field=models.CharField(choices=[('weapon', 'Weapon'), ('armor', 'Armor'), ('consumable', 'Consumable'), ('tool', 'Tool'), ('misc', 'Misc'), ('magic', 'Magic'), ('artifact', 'Artifact'), ('quest', 'Quest'), ('key', 'Key'), ('currency', 'Currency'), ('container', 'Container'), ('clothing', 'Clothing'), ('food', 'Food'), ('drink', 'Drink'), ('vehicle', 'Vehicle'), ('animal', 'Animal'), ('plant', 'Plant'), ('furniture', 'Furniture'), ('jewelry', 'Jewelry'), ('book', 'Book'), ('music', 'Music'), ('art', 'Art'), ('gem', 'Gem'), ('mineral', 'Mineral'), ('metal', 'Metal'), ('wood', 'Wood'), ('stone', 'Stone'), ('leather', 'Leather'), ('cloth', 'Cloth'), ('paper', 'Paper'), ('glass', 'Glass'), ('plastic', 'Plastic'), ('bone', 'Bone'), ('shell', 'Shell'), ('hide', 'Hide'), ('feather', 'Feather'), ('scale', 'Scale'), ('fur', 'Fur'), ('spice', 'Spice'), ('herb', 'Herb'), ('oil', 'Oil'), ('ink', 'Ink'), ('dye', 'Dye'), ('paint', 'Paint'), ('potion', 'Potion'), ('scroll', 'Scroll'), ('spell', 'Spell'), ('wand', 'Wand')], max_length=50),
        ),
    ]
