# Generated by Django 4.1.7 on 2023-04-15 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caravan', '0005_trader_description_alter_biome_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trader',
            name='items',
            field=models.ManyToManyField(blank=True, to='caravan.item'),
        ),
    ]
