# Generated by Django 4.1.7 on 2023-04-15 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caravan', '0006_trader_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='biomes',
            field=models.ManyToManyField(blank=True, null=True, to='caravan.biome'),
        ),
        migrations.AlterField(
            model_name='item',
            name='job_requirements',
            field=models.ManyToManyField(blank=True, null=True, to='caravan.job'),
        ),
        migrations.CreateModel(
            name='TraderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(blank=True, null=True)),
                ('price', models.PositiveIntegerField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caravan.item')),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caravan.trader')),
            ],
        ),
    ]
