# Generated by Django 4.1.7 on 2023-04-17 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caravan', '0007_alter_item_biomes_alter_item_job_requirements_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='caravan_trader_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(blank=True, null=True)),
                ('price', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'caravan_trader_items',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='item',
            name='biomes',
            field=models.ManyToManyField(blank=True, to='caravan.biome'),
        ),
        migrations.AlterField(
            model_name='item',
            name='job_requirements',
            field=models.ManyToManyField(blank=True, to='caravan.job'),
        ),
        migrations.DeleteModel(
            name='TraderItem',
        ),
    ]
