# Generated by Django 4.1.7 on 2023-04-18 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caravan', '0008_caravan_trader_items_alter_item_biomes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caravan.item')),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caravan.trader')),
            ],
            options={
                'db_table': 'caravan_trader_items',
                'unique_together': {('trader', 'item')},
            },
        ),
        migrations.DeleteModel(
            name='caravan_trader_items',
        ),
        migrations.AlterField(
            model_name='trader',
            name='items',
            field=models.ManyToManyField(blank=True, through='caravan.TraderItem', to='caravan.item'),
        ),
    ]
