# Generated by Django 4.1.7 on 2023-04-18 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caravan', '0009_traderitem_delete_caravan_trader_items_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='traderitem',
            table=None,
        ),
    ]
